app/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home_page

urlpatterns = [
    path('', home_page, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
]

events/urls.py
from django.urls import path

from events.views import EventDetailView, CreateEventIdeaView, UpvoteIdeaView

app_name = "events"
urlpatterns = [
    path("<int:event_id>/", EventDetailView.as_view(), name = 'event-detail'),
    path("<int:event_id>/ideas/", CreateEventIdeaView.as_view(), name = 'create-idea'),
    path("<int:event_id>/ideas/<int:idea_id>/", UpvoteIdeaView.as_view(), name = 'upvote-idea'),
]

events/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from common.models import BaseModel


class Event(BaseModel):
    organizer = models.ForeignKey('accounts.CustomUser', on_delete = models.CASCADE, related_name = 'events',
                                  related_query_name = 'event')

    title = models.CharField(_('title'), max_length = 255)
    overview = models.TextField(_('overview'))

    start_date = models.DateTimeField(_('start date'))
    end_date = models.DateTimeField(_('end date'))

    is_approved = models.BooleanField(default = False)

    def __str__(self):
        return self.title


class Idea(BaseModel):
    my_event = models.ForeignKey(Event, related_name = 'ideas', related_query_name = 'idea', on_delete = models.CASCADE)
    owner = models.ForeignKey('accounts.CustomUser', related_name = 'ideas', related_query_name = 'idea',
                              on_delete = models.CASCADE)
    title = models.CharField(_('title'), max_length = 255)
    overview = models.TextField(_('overview'))

    def __str__(self):
        return self.title


class IdeaUpvote(BaseModel):
    my_idea = models.ForeignKey(Idea, related_name = 'upvotes', related_query_name = 'upvote',
                                on_delete = models.CASCADE)
    user = models.ForeignKey('accounts.CustomUser', related_name = 'upvotes', related_query_name = 'upvote',
                             on_delete = models.CASCADE)

    class Meta:
        unique_together = ('my_idea', 'user')

    def __str__(self):
        return f"{self.user} likes {self.my_idea.title}"

events/forms.py
from django import forms

from events.models import Idea


class CreateideaFrom(forms.ModelForm):
    class Meta:
        model = Idea
        fields = (
            'title',
            'overview',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(attrs = {
            'class': 'form-control',
            'placeholder': 'Idea Title'
        })
        self.fields['overview'].widget = forms.Textarea(attrs = {
            'class': 'form-control',
            'placeholder': 'Idea Overview'
        })

events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import OuterRef, Exists
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from .forms import CreateideaFrom
from .models import Event, Idea, IdeaUpvote


class EventDetailView(LoginRequiredMixin, View):
    def get(self, request, event_id):
        try:
            event = Event.objects.get(pk = event_id)
        except Event.DoesNotExist:
            return HttpResponse('Event does not exist')

        ideas = event.ideas.all().annotate(
            is_liked = Exists(
                IdeaUpvote.objects.filter(user = request.user, my_idea = OuterRef('pk'))
            )
        )
        context = {
            "event": event,
            "idea_form": CreateideaFrom(),
            "ideas": ideas,
        }

        return render(request, "event_detail.html", context = context)


class CreateEventIdeaView(LoginRequiredMixin, View):
    def post(self, request, event_id):
        try:
            event = Event.objects.get(pk = event_id)
        except Event.DoesNotExist:
            return HttpResponse('Event does not exist')

        form = CreateideaFrom(request.POST)
        if form.is_valid():
            Idea.objects.create(
                owner = request.user,
                my_event = event,
                title = form.cleaned_data['title'],
                overview = form.cleaned_data['overview'],
            )

        return redirect('events:event-detail', event_id = event.id)


class UpvoteIdeaView(LoginRequiredMixin, View):
    def post(self, request, event_id, idea_id):
        try:
            idea = Idea.objects.get(id = idea_id, my_event_id = event_id)
        except Idea.DoesNotExist:
            return HttpResponse("Idea does not exist")

        IdeaUpvote.objects.create(
            my_idea = idea,
            user = request.user
        )

        return redirect("events:event-detail", event_id = event_id)

events/templates/event_detail.html
{% extends 'base.html' %}
{% block title %} Event Detail Page {% endblock title %}

{% block content %}

<div class="mt-4">
    <div class="d-xl-flex col-xl">
        <div>
            <img src="https://thumbs.dreamstime.com/b/simple-website-html-code-colourful-tags-browser-view-dark-background-orange-text-183366184.jpg"
                 class="rounded mx-auto d-block" width="300" alt="***">
        </div>
        <div class="col align-content-end flex-wrap text-center text-xl-start ms-3">
            <h1>{{ event.title }}</h1>
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-overview" type="button" role="tab" aria-controls="nav-overview"
                            aria-selected="true">Overview
                    </button>
                    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-ideas"
                            type="button" role="tab" aria-controls="nav-ideas" aria-selected="false">Ideas
                    </button>
                    <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
                            type="button" role="tab" aria-controls="nav-contact" aria-selected="false">****
                    </button>
                </div>
            </nav>
        </div>
    </div>

    <div class="tab-content mt-4" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-overview" role="tabpanel" aria-labelledby="nav-overview-tab">
            {{ event.overview }}
        </div>
        <div class="tab-pane fade" id="nav-ideas" role="tabpanel" aria-labelledby="nav-ideas-tab">
            {% if request.user.is_authenticated %}
            <div class="row w-50 mb-3">
                <form method="post" action="{% url 'events:create-idea' event.id %}">
                    {% csrf_token %}
                    {{ idea_form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            {% endif %}

            {% for idea in ideas %}
            <div id="ideas-list" class="row">
                <form id="upvote-idea-{{ idea.id }}" method="post" type="hidden"
                      action="{% url 'events:upvote-idea' event.id idea.id %}">
                    {% csrf_token %}
                </form>
                <div class="col-md-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ idea.title }}</h5>
                            {% if idea.is_liked %}
                            <i role="button" class="fa-solid fa-heart"></i>
                            {% else %}
                            <i role="button" class="fa-regular fa-heart" onclick="upvoteIdea({{ idea.id }})"></i>
                            {% endif %}
                            <span class="badge text-bg-secondary">{{ idea.upvotes.count }}</span>
                            <p class="card-text">{{ idea.overview }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
    </div>

</div>
<script>
    function upvoteIdea(idea_id) {
        document.getElementById(`upvote-idea-${idea_id}`).submit();
    }
</script>
{% endblock %}