accounts/urls.py
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView


app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home_page

urlpatterns = [
    path('', home_page, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
]

events/urls.py
from django.urls import path

from events.views import EventDetailView, CreateEventIdeaView, UpvoteIdeaView

app_name = "events"
urlpatterns = [
    path("<int:event_id>/", EventDetailView.as_view(), name = 'event-detail'),
    path("<int:event_id>/ideas/", CreateEventIdeaView.as_view(), name = 'create-idea'),
    path("<int:event_id>/ideas/<int:idea_id>/", UpvoteIdeaView.as_view(), name = 'upvote-idea'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
{% include "header.html" %}
<main class="container">
    {% block content %}{% endblock content %}
</main>
<script>
    function updateTheme() {
    const colorMode = window.matchMedia("(prefers-color-scheme: dark)").matches ?
        "dark" :
        "light";
    document.querySelector("html").setAttribute("data-bs-theme", colorMode);
    }

    updateTheme()

    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', updateTheme)
</script>
<script src="https://kit.fontawesome.com/1c24932d74.js" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand mb-0 h1" href="{% url 'home' %}">Hackogi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active {% endif %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/events' %}active {% endif %}" href="#">Events</a>
                </li>
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}

                <a href="{% url 'accounts:logout' %}" class="btn btn-sm btn-danger text-decoration-none">Logout</a>
                {% else %}
                <a class="btn btn-sm btn-success text-decoration-none" href="{% url 'accounts:login' %}" role="button">Login</a>
                {% endif %}
                <a class="btn btn-sm btn-warning text-decoration-none" href="{% url 'accounts:register' %}"
                   role="button">Register</a>
            </div>
        </div>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home Page {% endblock title %}

{% block content %}

<div class="p-4 p-md-5 mt-4 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
        <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
        <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently
            about what’s most interesting in this post’s contents.</p>
        <p class="lead mb-0"><a href="#" class="text-body-emphasis fw-bold">Continue reading...</a></p>
    </div>
</div>

<h2 class="mt-2">Active Hackathons </h2>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for hackathon in active_hackathons %}
    <div class="col">
        <div class="card shadow-sm">
            <img src="https://thumbs.dreamstime.com/b/simple-website-html-code-colourful-tags-browser-view-dark-background-orange-text-183366184.jpg"
                 class="bd-placeholder-img card-img-top" width="100%" height="225" alt="hackathon image">
            <div class="card-body">
                <a href="{% url 'events:event-detail' hackathon.id %}"><p class="card-text">{{ hackathon.title }}</p>
                </a>
                {{hackathon.overview}}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<h2 class="mt-2"> Upcoming Hackathons </h2>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for hackathon in upcame_hackathons %}
    <div class="col">
        <div class="card shadow-sm">
            <img src="https://thumbs.dreamstime.com/b/simple-website-html-code-colourful-tags-browser-view-dark-background-orange-text-183366184.jpg"
                 class="bd-placeholder-img card-img-top" width="100%" height="225" alt="hackathon image">
            <div class="card-body">
                <a href="{% url 'events:event-detail' hackathon.id %}"><p class="card-text">{{ hackathon.title }}</p>
                </a>
                {{hackathon.overview}}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<h2 class="mt-2">Past Hackathons </h2>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for hackathon in past_hackathons %}
    <div class="col">
        <div class="card shadow-sm">
            <img src="https://thumbs.dreamstime.com/b/simple-website-html-code-colourful-tags-browser-view-dark-background-orange-text-183366184.jpg"
                 class="bd-placeholder-img card-img-top" width="100%" height="225" alt="hackathon image">
            <div class="card-body">
                <a href="{% url 'events:event-detail' hackathon.id %}"><p class="card-text">{{ hackathon.title }}</p>
                </a>
                {{hackathon.overview}}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}